name = "my-driver-dashboard"
main = "worker.js"
compatibility_date = "2024-07-01"

[vars]
# You'll need to set this secret in the Cloudflare dashboard
# It's better to manage secrets in the dashboard than in this file
# ADMIN_PASSWORD = "your_secure_password_here"

[[kv_namespaces]]
binding = "DRIVER_APP_DATA"
id = "your-kv-namespace-id"

[site]
bucket = "./"

[triggers]
crons = []
