# wrangler.toml
name = 'driver-auth-worker'
main = "worker.js"
compatibility_date = "2025-08-04"

[[kv_namespaces]]
binding = "DRIVER_APP_DATA"
id = "your-kv-namespace-id"

[site]
bucket = "./"

[triggers]
crons = []
